[package]
name = "teaplc"
version = "0.1.0"
edition = "2021"

[build-dependencies]
lalrpop = "0.22.0"

[dependencies]
indexmap = "2.7.0"
lalrpop-util = { version = "0.21.0", features = ["lexer", "unicode"] }
